#pragma once

// gets removed in the build process
#include "defs-test.hpp"

#define HYPRSHELL_PLUGIN_NAME "_HYPRSHELL_PLUGIN_NAME_"
#define HYPRSHELL_PLUGIN_AUTHOR "_HYPRSHELL_PLUGIN_AUTHOR_"
#define HYPRSHELL_PLUGIN_DESC "_HYPRSHELL_PLUGIN_DESC_"
#define HYPRSHELL_PLUGIN_VERSION "_HYPRSHELL_PLUGIN_VERSION_"

#define HYPRSHELL_PRINT_START _HYPRSHELL_PRINT_START_

#define HYPRSHELL_SWTICH_RELEASE_KEYCODE _HYPRSHELL_SWTICH_RELEASE_KEYCODE_
#define HYPRSHELL_PROGRAM_CLOSE_SWITCH R"(_HYPRSHELL_PROGRAM_CLOSE_SWITCH_)"
#define HYPRSHELL_PROGRAM_ESCAPE R"(_HYPRSHELL_PROGRAM_ESCAPE_)"
