#define HYPRSHELL_PLUGIN_NAME "@HYPRSHELL_PLUGIN_NAME@"
#define HYPRSHELL_PLUGIN_AUTHOR "@HYPRSHELL_PLUGIN_AUTHOR@"
#define HYPRSHELL_PLUGIN_DESC "@HYPRSHELL_PLUGIN_DESC@"
#define HYPRSHELL_PLUGIN_VERSION "@HYPRSHELL_PLUGIN_VERSION@"