#pragma once

#include <hyprland/src/plugins/PluginAPI.hpp>

const CHyprColor RED{1.0, 0.2, 0.2, 1.0};
const CHyprColor GREEN{0.2, 1.0, 0.2, 1.0};

struct PluginDescriptionInfo {
    std::string name;
    std::string description;
    std::string author;
    std::string version;
};

#define SWITCHAROO_PLUGIN_NAME "$SWITCHAROO_PLUGIN_NAME$"
#define SWITCHAROO_PLUGIN_AUTHOR "$SWITCHAROO_PLUGIN_AUTHOR$"
#define SWITCHAROO_PLUGIN_DESC "$SWITCHAROO_PLUGIN_DESC$"
#define SWITCHAROO_PLUGIN_VERSION "$SWITCHAROO_PLUGIN_VERSION$"

#define SWITCHAROO_PRINT_DEBUG $SWITCHAROO_PRINT_DEBUG$
#define SWITCHAROO_PRINT_DEBUG_DEBUG 0
#define SWITCHAROO_SOCKET_PATH "$SWITCHAROO_SOCKET_PATH$"

#define SWITCHAROO_SWTICH_XKB_MOD_L $SWITCHAROO_SWTICH_XKB_MOD_L$
#define SWITCHAROO_SWTICH_XKB_MOD_R $SWITCHAROO_SWTICH_XKB_MOD_R$
#define SWITCHAROO_SWITCH_KEY "$SWITCHAROO_SWITCH_KEY$"

#define SWITCHAROO_CLOSE R"($SWITCHAROO_CLOSE$)"
#define SWITCHAROO_OPEN_SWITCH R"($SWITCHAROO_OPEN_SWITCH$)"
#define SWITCHAROO_OPEN_SWITCH_REVERSE R"($SWITCHAROO_OPEN_SWITCH_REVERSE$)"

// gets removed in the build process
#include "defs-test.h"
