name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install gtk4-layer-shell
        working-directory: /tmp
        run: |
          sudo apt-get update
          sudo apt -y install git libglib2.0-dev libgraphene-1.0-dev meson ninja-build libwayland-dev libgtk-4-dev gobject-introspection libadwaita-1-dev libgirepository1.0-dev python3 valac
          git clone https://github.com/wmww/gtk4-layer-shell
          cd /tmp/gtk4-layer-shell
          meson setup build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig
      - name: Install cargo-workspaces
        run: |
          cargo install cargo-workspaces
      - name: Publish to crates.io
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git fetch --tags origin hyprshell
          git checkout ${{ github.ref }} -b hyprshell
          echo "removing old tag"
          git tag -d ${{ github.ref_name }}
          version=$(echo ${{ github.ref_name }} | sed 's/v//')
          cargo ws publish custom $version -m "chore(release): bump rust versions to $version" --no-individual-tags --allow-branch hyprshell --exact --yes --force "hyprshell*" --token ${{ secrets.CRATES_TOKEN }}
          git push origin hyprshell
          git push -f --tags origin hyprshell
        env:
          HYPRSHELL_SOCAT_PATH: ''