name: test

on:
  push:
    branches-ignore:
      - 'release-please-**'
      - 'hyprshell-release'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: "ubuntu-latest"
    container:
      image: alpine:latest
    steps:
      - name: Install git and other dependencies
        run: apk add --no-cache git tar pkgconf cargo gtk4.0-dev gtk4-layer-shell-dev bash
      - uses: actions/checkout@v4
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: ./scripts/test.sh

  clippy:
    name: Run Clippy
    runs-on: "ubuntu-latest"
    container:
      image: alpine:latest
    steps:
      - name: Install git and other dependencies
        run: apk add --no-cache git tar pkgconf cargo gtk4.0-dev gtk4-layer-shell-dev rust-clippy
      - uses: actions/checkout@v4
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Run Clippy
        run: cargo clippy --all-targets