name: test

on:
  push:
    branches-ignore:
      - 'release-please-**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: "ubuntu-latest"
    container:
      image: archlinux:base
    steps:
      - name: Install git and other dependencies
        run: pacman -Syu --noconfirm git pkgconf rust gtk4 gtk4-layer-shell
      - uses: actions/checkout@v4
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: ./scripts/test.sh

  clippy:
    name: Run Clippy
    runs-on: "ubuntu-latest"
    container:
      image: archlinux:base
    steps:
      - name: Install git and other dependencies
        run: pacman -Syu --noconfirm git pkgconf rust gtk4 gtk4-layer-shell
      - uses: actions/checkout@v4
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Run Clippy
        run: cargo clippy --all-targets