name: test

on:
  push:
    branches-ignore:
      - 'release-please-**'
      - 'switcharoo-release'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run build tests
    runs-on: "ubuntu-latest"
    container:
      image: ghcr.io/h3rmt/actions-image:latest
      options: --privileged
    if: github.ref == 'refs/heads/switcharoo'
    steps:
      - run: rustup default stable
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          prefix-key: switcharoo
          cache-on-failure: true
      - name: Build binary for x86_64-unknown-linux-gnu
        run: |
          ./scripts/ci/install-gtk4-layer-shell.sh
          ./scripts/ci/build-x86.sh
      - name: Build binary for aarch64-unknown-linux-gnu
        run: |
          ./scripts/ci/install-gtk4-layer-shell-aarch64.sh
          ./scripts/ci/build-aarch64.sh

