name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 2 */14 * 1' # runs every two weeks on Monday at 02:00

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/update-flake-lock@v25
        with:
          pr-title: "Update Nix flake inputs"
          pr-assignees: H3rmt